language: node_js
node_js:
- lts/*
script:
- npm run deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_69dd79a22683_key -iv $encrypted_69dd79a22683_iv
  -in TravisCI.enc -out ~\/.ssh/TravisCI -d
