language: node_js
node_js:
  - lts/*
script:
  - npm run deploy
deploy:
  provider: pages
  skip-cleanup: true
  # local_dir: .vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master
# before_install:
#   - openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv -in deploy_key.enc -out ./deploy_key -d
#   - eval `ssh-agent -s`
#   - chmod 400 ./deploy_key
#   - ssh-add ./deploy_key